### PR TITLE
Update player.js

### PR DESCRIPTION
**Pull request by Fastxyz**
I've fixed the Insane 1 line.

Before:

```js
if (theNumber === 5) return { level: "Insane", id: theNumber, insane: false, levelsLeft: 21-theNumber }
if (theNumber === 6) return { level: "Insane I", id: theNumber, insane: 0, levelsLeft: 21-theNumber }
```

After:

```js
if (theNumber === 5) return { level: "Insane", id: theNumber, insane: 1, levelsLeft: 21-theNumber }
```

### CODE REVIEW

**Comment by Fastxyz** [comment]
@alputv

**Comment by alputv** [comment]
In game, it is Insane isn't it?

**Comment by Fastxyz** [comment]
> In game, it is Insane isn't it?

Yes, but in the files it was 2 Insane 1 (Insane and Insane I)

**Comment by alputv** [comment]
Thanks for the report & pr! 🙂

**Pull request merged**
