### PR TITLE
Updated specialLevels function

### PR DESCRIPTION
**Pull request by Fastxyz**
For people using a language system, this patch will be useful.

Example:

```js
const insaneEN = 'Insane';
const insaneFR = 'Maniaque';
const insanePT = 'Insano';

// If I want to send the message in Portuguese
message.channel.send(`${insanePT} ${player.bestRoboRumbleLevel.otherInsane}` // Insano VI
```

### CODE REVIEW

**Comment by Fastxyz** [comment]
@alputv

**Comment by alputv** [comment]
Good idea! But in every single language it is different. We can add a language system but it will need some more updates. I am currently in mobile, so it is not possible. Maybe added later...

Keep this Pr open 👍

**Comment by Fastxyz** [comment]
> Good idea! But in every single language it is different. We can add a language system but it will need some more updates. I am currently in mobile, so it is not possible. Maybe added later...
> 
> Keep this Pr open

Im not asking you to create a language system. The constants that I put its an example from a command file that the user has.  If he have a language system, he will use the `bestRoboRumbleLevel` like I did. If not, he will use the `bestRoboRumbleLevel` with the `level` property.

**Comment by alputv** [comment]
> > Good idea! But in every single language it is different. We can add a language system but it will need some more updates. I am currently in mobile, so it is not possible. Maybe added later...
> > Keep this Pr open
> 
> Im not asking you to create a language system. The constants that I put its an example from a command file that the user has. If he have a language system, he will use the `bestRoboRumbleLevel` like I did. If not, he will use the `bestRoboRumbleLevel` with the `level` property.

Hmm, it will be good i guess.. But after thinking about it more, i think it is a really good touch! Thanks ❤

**Pull request merged**
